name: Simple Deploy Pulero Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 185.139.1.231
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /pulero-mandala

          # Cria um backup dos dados antes de atualizar
          tar -czf backup-$(date +%F).tar.gz data tokens

          # Puxa as últimas mudanças do repositório
          git pull origin main

          # Para e remove qualquer container com o nome 'pb', se existir
          if docker ps -a --filter "name=pb" --format '{{.ID}}' | grep -q .; then
            docker stop pb
            docker rm pb
          fi

          # Remove imagens antigas da 'pb' para evitar conflitos
          docker rmi pb || true

          # Cria uma nova imagem com uma tag única para evitar problemas de cache
          docker build -t pb:$(git rev-parse --short HEAD) .

          # Executa o novo container
          docker run -d --name pb pb:$(git rev-parse --short HEAD)
